name: XSaiga
version: 1.6.1.0
synopsis: An implementation of a polynomial-time top-down parser suitable for NLP
homepage: http://speechweb2.cs.uwindsor.ca/solarman4/demo_sparql.html
license: BSD3
license-file: LICENSE
author: Dr. Rahmatullah Hafiz, Dr. Richard Frost <rfrost@cogeco.ca>, Shane Peelar, Paul Callaghan, Eric Matthews
maintainer: Shane Peelar <peelar@uwindsor.ca>
category: Parsing, Natural Language Processing, Memoization, Parser Combinators, Attribute Grammars, Text
github: InBetweenNames/Solarman

build-type: Simple

description: |
  This package contains a Haskell implementation of the X-SAIGA project's parser combinators. The combinators
  enable fully-general attribute grammars to be implemented as executable specifications. Although the parser
  is top-down, and therefore highly modular, left-recursive productions are allowed and fully-general synthesized
  and inherited attribute dependencies are also allowed. The parse tree, which is decorated with attribute values,
  is built as a compact Tomita-style graph. Lazy evaluation enables attribute values to be evaluated only as needed.
  Time and space complexity are both O(n^4) where n is the length of the input. An example natural-language interface (called Solarman)
  to a semantic-web style RDF triplestore with approximately 3,000 facts about the solar system has been built
  as an executable specification of an attribute grammar. Solarman is included in this archive.
  Solarman computes answers to queries using an event-based denotational semantics which is based on Montague and Davidsonian semantics.
  A web site [3] has been created so that readers can enter queries and find out more about Solarman.
  .
  \[1] <http://cs.uwindsor.ca/~richard/PUBLICATIONS/PADL_08.pdf>
  .
  \[2] <http://cs.uwindsor.ca/~richard/PUBLICATIONS/PADL_10.pdf>
  .
  \[3] <http://speechweb2.cs.uwindsor.ca/solarman4/demo_sparql.html>

dependencies:
  - base >=4.6 && < 5
  - pretty >= 1.1
  - hsparql >= 0.3.6
  - rdf4h >= 1.2
  - text >= 0.11
  - containers >= 0.5
  - network
  - bifunctors
  - mtl
  - bytestring
  - cgi
  - fastcgi
  - random

default-extensions:
  - DoAndIfThenElse
  - OverloadedStrings
  - FlexibleInstances
  - NoMonomorphismRestriction

library:
  source-dirs: src
  exposed-modules:
    - XSaiga.Getts
    - XSaiga.AGParser2
    - XSaiga.TypeAg2
    - XSaiga.SolarmanTriplestore
    #- XSaiga.Interactive
    - XSaiga.LocalData
    - XSaiga.CGI

executables:
  solarman.cgi:
   source-dirs: driver
   main: Main.hs
   dependencies: XSaiga
